spring:
  application:
    client-http:
      address:
        url: http://localhost:8082/addresses
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
